require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Store emails for preview at /letter_opener instead of sending
  config.action_mailer.delivery_method = :letter_opener_web

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Route Solid Queue's models to the dedicated queue database
  # (mirrors production so deliver_later jobs land where bin/jobs polls).
  config.solid_queue.connects_to = { database: { writing: :queue } }

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Hotwire Spark: live reload for views, components, and CSS
  config.hotwire.spark.html_paths += %w[ app/components ]
  config.hotwire.spark.css_paths = %w[ app/assets/builds ]

  # Bullet: detect N+1 queries and unused eager loading
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = true

    # WorkspacesController#index queries memberships first then joins+preloads
    # workspace so it can sort by `memberships.last_accessed_at` (Path AA pinned-
    # current row). Bullet flags `Membership => [:workspace]` as unused eager
    # loading because the join already aliases workspaces into the SQL, so its
    # detector treats the includes-side preload as redundant — but the view
    # still needs the preloaded workspace per row to render name + icon without
    # an N+1. Mirrors the test.rb safelist added in Path AA Task 6 (7c7053a).
    Bullet.add_safelist(type: :unused_eager_loading,
                        class_name: "Membership",
                        association: :workspace)

    # The inner `workspace.memberships: [:role, :user]` preload feeds
    # `Workspace#owners` (loaded?-aware at fb89ac4), which short-circuits when
    # no row hits the owner-check path on the workspaces index. When the
    # short-circuit fires for every row in a page, the inner :user (and
    # transitive :workspace) preload goes unused and Bullet flags it. We
    # can't know per-row whether the owner-check will fire until policy
    # evaluation, so the preload is intentionally pessimistic — accept the
    # false positive rather than pay an N+1 on the rows that do need owners.
    Bullet.add_safelist(type: :unused_eager_loading,
                        class_name: "Membership",
                        association: :user)
  end
end
